// <auto-generated />
using EmployeeRegistration.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeRegistration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201230100338_seedemployeestable")]
    partial class seedemployeestable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeRegistration.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Genders");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<long>("Phone");

                    b.Property<string>("Question")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Landon",
                            Email = "Pat.Collumn@abc.com",
                            FirstName = "Pat",
                            Genders = 0,
                            LastName = "Collumn",
                            Password = "abcd@123",
                            Phone = 9923128577L,
                            Question = "In which city you boarn?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "MVM",
                            Email = "Colin.Bell@abc.com",
                            FirstName = "Colin",
                            Genders = 0,
                            LastName = "Bell",
                            Password = "abcd@456",
                            Phone = 9923128578L,
                            Question = "High school name"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "boxer",
                            Email = "Mery.John@abc.com",
                            FirstName = "Mery",
                            Genders = 1,
                            LastName = "John",
                            Password = "abcd@456789",
                            Phone = 9923128580L,
                            Question = "Your pet name"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
